using System.Collections.Generic;
using Technie.PhysicsCreator.Rigid;
using UnityEngine;

namespace Technie.PhysicsCreator.QHull
{
	public class Vertex
	{
		public Point3d pnt;

		public int index;

		public Vertex prev;

		public Vertex next;

		public Face face;

		public Vertex()
		{
			pnt = new Point3d();
		}

		public Vertex(double x, double y, double z, int idx)
		{
			pnt = new Point3d(x, y, z);
			index = idx;
		}
	}
}
namespace Technie.PhysicsCreator
{
}
namespace Technie.PhysicsCreator.QHull
{
}
namespace Technie.PhysicsCreator
{
}
namespace Technie.PhysicsCreator
{
	public class HullMapping
	{
		public Hull sourceHull;

		public Collider generatedCollider;

		public MeshCollider[] autoGeneratedColliders;

		public RigidColliderCreatorChild targetChild;

		public RigidColliderCreatorChild[] targetAutoGeneratedChilds;

		public void AddAutoChild(RigidColliderCreatorChild newChild, MeshCollider newCollider)
		{
			if (newChild != null)
			{
				List<RigidColliderCreatorChild> list = new List<RigidColliderCreatorChild>();
				if (targetAutoGeneratedChilds != null)
				{
					list.AddRange(targetAutoGeneratedChilds);
				}
				if (!list.Contains(newChild))
				{
					list.Add(newChild);
					targetAutoGeneratedChilds = list.ToArray();
				}
			}
			if (newCollider != null)
			{
				List<MeshCollider> list2 = new List<MeshCollider>();
				if (autoGeneratedColliders != null)
				{
					list2.AddRange(autoGeneratedColliders);
				}
				if (!list2.Contains(newCollider))
				{
					list2.Add(newCollider);
					autoGeneratedColliders = list2.ToArray();
				}
			}
		}
	}
}
namespace Technie.PhysicsCreator.QHull
{
}
